version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: carteira_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: carteira_digital
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: carteira_redis
    ports:
      - '6379:6379'

  localstack:
    image: localstack/localstack
    container_name: carteira_localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - EAGER_SERVICE_LOADING=1

volumes:
  postgres_data:
