apiVersion: v1
kind: Secret
metadata:
  name: carteira-secrets
  namespace: carteira-digital
type: Opaque
stringData:
  database-host: 'localhost'
  database-port: '5432'
  database-user: 'admin'
  database-password: 'admin123'
  database-name: 'carteira_digital'
  redis-host: 'localhost'
  redis-port: '6379'
  jwt-secret: 'sua_chave_secreta_aqui'
  aws-endpoint: 'http://localhost:4566'
  sqs-queue-url: 'http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/transferencias'
