apiVersion: v1
kind: Service
metadata:
  name: carteira-digital
  namespace: carteira-digital
spec:
  selector:
    app: carteira-digital
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer # exp√µe externamente com balanceamento de carga
